services:
  - type: web
    name: noaesperanza-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DB_NAME
        value: noa_db
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: noa-db.cna4aiiyochz.us-east-2.rds.amazonaws.com
      - key: DB_PORT
        value: "5432"
      - key: OPENAI_API_KEY
        sync: false
      - key: GPT_AVALIACAO_MODEL
        sync: false
      - key: GPT_ONBOARDING_ASSISTANT_ID
        sync: false
